title: "Enter the issue summary"
labels: ["Jira"]
body:
  - type: markdown
    attributes:
      value: "## Summary"
  - type: input
    id: summary
    attributes:
      label: "Enter a brief summary"
      description: "A short summary of the issue."
      placeholder: "E.g., Implement feature X"
  - type: markdown
    attributes:
      value: "## Description"
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Provide a detailed description of the issue or task."
      placeholder: "Describe the problem, task, or feature request."
  - type: markdown
    attributes:
      value: "## Priority"
  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options:
        - "Low"
        - "Medium"
        - "High"
  - type: markdown
    attributes:
      value: "## Status"
  - type: dropdown
    id: status
    attributes:
      label: "Status"
      options:
        - "To Do"
        - "In Progress"
        - "Done"
  - type: markdown
    attributes:
      value: "## Assignee"
  - type: input
    id: assignee
    attributes:
      label: "Assign this to"
      description: "Assign the task to a GitHub user."
      placeholder: "@username"
