title: "Topic you Learned about?"
labels: ["FusionFriday", "CloudOperations"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing what you've learned on Fusion Friday! Please fill out this form as completely as possible.
        **Note:** The Learning Topic should be the same as the title you entered above.

  - type: input
    id: title
    attributes:
      label: Learning Topic
      description: What did you learn today? (Make sure this matches your discussion title)
      placeholder: "I learned about..."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description of Learning
      description: Provide a detailed description of what you have learned.
      placeholder: "Today, I learned..."
    validations:
      required: true

  - type: textarea
    id: benefit
    attributes:
      label: How does it benefit BMO?
      description: Explain how your learning benefits the Office of Management and Budget.
      placeholder: "This benefits BMO by..."
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Personal Takeaways
      description: What were your key takeaways from this learning experience?
      placeholder: "The key takeaway for me was..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Poll: How valuable did you find this topic?

        - 👍 Like
        - 👎 Dislike
        - ❤️ Love it!
        - 🤔 Thought-Provoking
        - 🚀 Ready to apply
        - 📘 Informative, but needs more clarity

        React with the emoji that best reflects your thoughts on this topic. Your feedback helps us improve our learning sessions!

  - type: input
    id: poll_feedback
    attributes:
      label: Additional Feedback (Optional)
      description: Share any additional comments or suggestions.
      placeholder: "Any other thoughts on this topic..."
