title: "[Question] Enter your question here"
labels: ["Q&A"]
body:
  - type: markdown
    attributes:
      value: |
        Welcome to the Q&A section! Please fill out the form below to provide as much context as possible for your question so that others can help you more efficiently.

  - type: input
    id: question_title
    attributes:
      label: Question Title
      description: What is your question about?
      placeholder: "Enter a clear and concise question title"
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Please provide the full details of your question.
      placeholder: "Explain your question in detail..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context or Background Information
      description: Provide any background information or context that will help others understand your question.
      placeholder: "Include relevant details, such as what you’ve tried, errors you’ve encountered, etc."
    validations:
      required: true

  - type: textarea
    id: expected_answer
    attributes:
      label: Expected Outcome or Answer
      description: What outcome or answer are you expecting?
      placeholder: "Describe what you’re hoping to achieve with this answer..."
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information (Optional)
      description: Any other details you think might be helpful.
      placeholder: "Include any additional information or screenshots if needed"
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Agreement to Code of Conduct
      description: By submitting this question, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
