title: "VM Start/Stop Request"
labels: ["Provision"]
body:
  - type: markdown
    attributes:
      value: |
        ### VM Start/Stop Request
        Please fill out the information below to request a change in the power status of a virtual machine.

  - type: input
    id: vm_name
    attributes:
      label: VM Name
      description: Enter the name of the virtual machine you want to control.
      placeholder: "e.g., MyVirtualMachine"
    validations:
      required: true

  - type: input
    id: resource_group_name
    attributes:
      label: Resource Group Name
      description: Enter the resource group containing the virtual machine.
      placeholder: "e.g., MyResourceGroup"
    validations:
      required: true

  - type: dropdown
    id: power_status
    attributes:
      label: Power Status
      description: Select the desired power status for the VM.
      options:
        - start
        - stop
    validations:
      required: true

  - type: textarea
    id: justification
    attributes:
      label: Justification
      description: Provide a reason for starting or stopping the VM.
      placeholder: "e.g., Testing server readiness for deployment."
    validations:
      required: true
