name: Label Discussions

on:
  discussion:
    types: [created]

jobs:
  label_discussion:
    runs-on: ubuntu-latest

    steps:
      - name: Add default label to discussion
        env:
          GH_TOKEN: ${{ secrets.G_TOKEN }}
          DISCUSSION_NUMBER: ${{ github.event.discussion.number }}
          LABEL: ideas
        run: |
          echo "Checking and adding label $LABEL to discussion #${{ github.event.discussion.number }}"

          # Fetch discussion details to check if a label exists
          DISCUSSION_LABELS=$(curl -s -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.discussion.number }} | jq '.labels')

          if [ "$DISCUSSION_LABELS" == "[]" ]; then
            echo "No labels found, adding label $LABEL."

            # Adding the label using GitHub API
            curl -X POST -H "Authorization: token $GH_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.discussion.number }}/labels \
              -d "{\"labels\":[\"$LABEL\"]}"
          else
            echo "Labels already exist: $DISCUSSION_LABELS"
          fi
