name: Delete Discussion

on:
  workflow_dispatch  # Trigger this workflow manually for demo purposes

jobs:
  delete_discussion:
    runs-on: ubuntu-latest

    steps:
      - name: Get Discussion ID
        env:
          GH_TOKEN: ${{ secrets.G_TOKEN }}
          DISCUSSION_NUMBER: 72  # Replace with the number of the discussion to delete
        run: |
          # Fetch the discussion ID using the discussion number
          DISCUSSION_ID=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -X POST \
            -d '{"query": "query { repository(owner: \"vchinnap\", name: \"CloudOps-Discussions\") { discussion(number: $DISCUSSION_NUMBER) { id } } }" }' \
            https://api.github.com/graphql | jq -r '.data.repository.discussion.id')

          echo "Discussion ID: $DISCUSSION_ID"

          # Delete the discussion
          curl -s -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -X POST \
            -d "{\"query\": \"mutation { deleteDiscussion(input: {discussionId: \\\"$DISCUSSION_ID\\\"}) { clientMutationId } }\"}" \
            https://api.github.com/graphql

          echo "Discussion #${{ env.DISCUSSION_NUMBER }} has been deleted."
