name: Label Discussions
on:
  discussion:
    types: [created]

jobs:
  label_discussion:
    runs-on: ubuntu-latest
    steps:
      - name: Add default label
        env:
          GH_TOKEN: ${{ secrets.G_TOKEN }}
          DISCUSSION_NUMBER: ${{ github.event.discussion.number }}
          LABEL: ideas
        run: |
          gh discussion edit $DISCUSSION_NUMBER --add-label "$LABEL"
