name: Auto-label Discussions

on:
  discussion:
    types: [created]

jobs:
  auto_label_discussion:
    runs-on: ubuntu-latest

    steps:
      - name: Add default label if missing
        env:
          GH_TOKEN: ${{ secrets.G_TOKEN }}
          DISCUSSION_NUMBER: ${{ github.event.discussion.number }}
          LABEL: ideas  # Set your default label here
        run: |
          echo "Checking discussion #${{ github.event.discussion.number }} for labels"

          # Fetch discussion details to check if a label exists
          DISCUSSION_LABELS=$(curl -s -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/discussions/${{ github.event.discussion.number }} | jq '.labels | length')

          if [ "$DISCUSSION_LABELS" -eq 0 ]; then
            echo "No labels found, adding default label: $LABEL"

            # Adding the label using GitHub Issues API (works for discussions too)
            curl -X POST -H "Authorization: token $GH_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${{ github.repository }}/discussions/${{ github.event.discussion.number }}/labels \
              -d "{\"labels\":[\"$LABEL\"]}"

            echo "Label $LABEL has been added to discussion #${{ github.event.discussion.number }}"
          else
            echo "Labels already exist for this discussion, no action taken."
          fi
