name: Auto-Assign Labels to Discussions Based on Category

on:
  discussion:
    types: [created, edited]

jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Assign Label based on Category
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
        run: |
          CATEGORY="${{ github.event.discussion.category.name }}"

          # Map categories to labels
          if [[ "$CATEGORY" == "Fusion Friday" ]]; then
            LABEL="FusionFriday"
          elif [[ "$CATEGORY" == "Q&A" ]]; then
            LABEL="CloudOperations"
          elif [[ "$CATEGORY" == "Ideas" ]]; then
            LABEL="Ideas"
          elif [[ "$CATEGORY" == "Channels" ]]; then
            LABEL="Channels"
          elif [[ "$CATEGORY" == "Announcements" ]]; then
            LABEL="Announcements"
          # Add more categories and corresponding labels as needed

          echo "Assigning label: $LABEL"

          # Apply the label to the discussion using the correct GitHub API for discussions
          gh api \
            -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/${{ github.repository }}/discussions/${{ github.event.discussion.number }}/labels \
            -f labels="[\"$LABEL\"]"
