name: Auto-Assign Labels to Discussions Based on Category

on:
  discussion:
    types: [created, edited]

jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Assign Label based on Category
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }} # Use your token here
        run: |
          CATEGORY="${{ github.event.discussion.category.name }}"

          if [[ "$CATEGORY" == "Fusion Friday" ]]; then
            LABEL="FusionFriday"
          elif [[ "$CATEGORY" == "Q&A" ]]; then
            LABEL="CloudOperations"
          elif [[ "$CATEGORY" == "Ideas" ]]; then
            LABEL="Ideas"
          elif [[ "$CATEGORY" == "Channels" ]]; then
            LABEL="Channels"
          # Add more categories and corresponding labels as needed

          # Apply the label to the discussion
          gh api \
            -X POST \
            -H "Authorization: token ${{ secrets.G_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/${{ github.repository }}/issues/${{ github.event.discussion.number }}/labels \
            -d '{"labels":["'"$LABEL"'"]}'
