name: Ensure Discussion Category

on:
  discussion:
    types: [created]

jobs:
  categorize_discussion:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch and ensure discussion is in "Ideas" category
        env:
          GH_TOKEN: ${{ secrets.G_TOKEN }}
        run: |
          echo "Fetching discussion details for #${{ github.event.discussion.number }}"

          # Fetch discussion details
          DISCUSSION_RESPONSE=$(curl -s -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/discussions/${{ github.event.discussion.number }})

          # Log the full discussion response for debugging purposes
          echo "Discussion response: $DISCUSSION_RESPONSE"

          # Extract the category name
          CATEGORY=$(echo "$DISCUSSION_RESPONSE" | jq -r '.category.name')

          # Print the category
          echo "Discussion category is: $CATEGORY"

          # Check if the discussion is not in the 'Ideas' category
          if [ "$CATEGORY" != "Ideas" ]; then
            echo "This discussion is not in the 'Ideas' category. Please update the category manually."

            # Provide instructions for manually updating the category
            echo "To move this discussion to the 'Ideas' category:"
            echo "1. Go to the discussion at: https://github.com/${{ github.repository }}/discussions/${{ github.event.discussion.number }}"
            echo "2. Click 'Edit' next to the discussion category."
            echo "3. Select 'Ideas' from the dropdown and save your changes."
          else
            echo "This discussion is already in the 'Ideas' category."
          fi
