name: Label Discussions
on:
  discussion:
    types: [created]

jobs:
  label_discussion:
    runs-on: ubuntu-latest
    permissions:
      discussions: write
    steps:
      - name: Add default label
        env:
          GH_TOKEN: ${{ secrets.G_TOKEN }}
          DISCUSSION_NUMBER: ${{ github.event.discussion.number }}
          LABEL: ideas
          REPO: ${{ github.repository }}
        run: |
          gh issue edit $DISCUSSION_NUMBER --add-label "$LABEL" --repo "$REPO"
