name: Auto-label Discussions

on:
  discussion:
    types: [created]

jobs:
  auto_label:
    runs-on: ubuntu-latest
    steps:
      - name: Check discussion labels and assign if empty
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }} # Make sure to use your token (G_TOKEN)
        run: |
          # Get the discussion details
          DISCUSSION_LABELS=$(curl -s -H "Authorization: token ${{ secrets.G_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/discussions/${{ github.event.discussion.node_id }} | jq -r '.label')
          
          if [ "$DISCUSSION_LABELS" == "null" ]; then
            echo "No labels found. Assigning a default label."
            curl -X POST -H "Authorization: token ${{ secrets.G_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.discussion.node_id }}/labels \
            -d '{"labels":["ideas"]}'
          else
            echo "Labels already assigned: $DISCUSSION_LABELS"
          fi
