name: Get Discussion Data

description: This GitHub Actions workflow retrieves detailed information about a specific discussion in a repository using GitHub GraphQL API.

on:
  workflow_dispatch:
    inputs:
      discussion_number: 
        description: 'The number of the discussion to retrieve'
        required: true
        type: string

jobs:
  get_discussion_data:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Complete Discussion Data
        env:
          GH_TOKEN: ${{ secrets.G_TOKEN }}
        run: |
          DISCUSSION_NUMBER=${{ github.event.inputs.discussion_number }}
          echo "Fetching discussion data for discussion number: $DISCUSSION_NUMBER"

          # Define the GraphQL query to fetch discussion details
          GRAPHQL_QUERY='{
            "query": "query { repository(owner: \\\"vchinnap\\\", name: \\\"CloudOps-Discussions\\\") { discussion(number: '$DISCUSSION_NUMBER') { id, title, body, category { name }, author { login }, createdAt, lastEditedAt, url, comments(first: 10) { nodes { author { login }, body, createdAt } } } } }"
          }'

          # Fetch the discussion details using GitHub GraphQL API
          DISCUSSION_DATA=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -X POST \
            -d "$GRAPHQL_QUERY" \
            https://api.github.com/graphql)

          # Format and print the discussion details nicely
          echo "Fetched Discussion Data:"
          echo "$DISCUSSION_DATA" | jq .
