name: Auto-label new discussions based on category

on:
  discussion:
    types: [created]

permissions:
  issues: write  # Grants permission to modify issues (discussions share label capabilities with issues)

jobs:
  label-discussion:
    runs-on: ubuntu-latest
    steps:
      - name: Debug - Log the discussion payload
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.G_TOKEN }}
          script: |
            // Log the entire payload to see the structure and details of the discussion
            console.log(JSON.stringify(context.payload, null, 2));

      - name: Apply labels based on category
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.G_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const discussionNumber = context.payload.discussion.number;
            const category = context.payload.discussion.category.name;

            console.log(`Discussion number: ${discussionNumber}`);
            console.log(`Category: ${category}`);

            let labels = [];

            // Apply specific labels based on the category
            if (category === "Ideas") {
              labels = ["Initiatives", "Ideas"];
            } else if (category === "Question and Answer") {
              labels = ["Question and Answer"];
            } else {
              labels = ["General"]; // Apply "General" label for all other categories
            }

            // Add the labels if there are any
            if (labels.length > 0) {
              console.log(`Applying labels: ${labels.join(', ')}`);
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: discussionNumber,
                labels
              });
            }
