name: Get Discussion Data

description: This GitHub Actions workflow retrieves detailed information about a specific discussion in a repository using GitHub REST API.

on:
  workflow_dispatch:
    inputs:
      discussion_number:
        description: 'The number of the discussion to retrieve'
        required: true
        type: string

jobs:
  get_discussion_data:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Complete Discussion Data
        env:
          GH_TOKEN: ${{ secrets.G_TOKEN }}
        run: |
          DISCUSSION_NUMBER=${{ github.event.inputs.discussion_number }}
          echo "Fetching discussion data for discussion number: $DISCUSSION_NUMBER"

          # Fetch the discussion details using GitHub REST API
          DISCUSSION_DATA=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/vchinnap/CloudOps-Discussions/discussions/$DISCUSSION_NUMBER)

          # Format and print the discussion details nicely
          echo "Fetched Discussion Data:"
          echo "$DISCUSSION_DATA" | jq .
