name: Categorize Discussions

on:
  discussion:
    types: [created]

jobs:
  categorize_discussion:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch and print discussion category
        env:
          GH_TOKEN: ${{ secrets.G_TOKEN }}
        run: |
          echo "Fetching discussion details for #${{ github.event.discussion.number }}"

          # Fetch discussion details
          DISCUSSION_RESPONSE=$(curl -s -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/discussions/${{ github.event.discussion.number }})

          # Log the full discussion response for debugging purposes
          echo "Discussion response: $DISCUSSION_RESPONSE"

          # Extract the category name
          CATEGORY=$(echo "$DISCUSSION_RESPONSE" | jq -r '.category.name')

          # Print the category
          echo "Discussion category is: $CATEGORY"

          # Optional: Based on the category, perform further actions here
          # For example:
          if [ "$CATEGORY" == "Ideas" ]; then
            echo "This is an 'Ideas' discussion."
            # Add further automation for discussions categorized as 'Ideas'
          else
            echo "This is not categorized as 'Ideas'."
          fi
