name: Auto-label Discussions

on:
  discussion:
    types: [created]

jobs:
  auto_label_discussion:
    runs-on: ubuntu-latest

    steps:
      - name: Add default label if missing
        env:
          GH_TOKEN: ${{ secrets.G_TOKEN }}
          LABEL: ideas  # Change this label to any default label you want
        run: |
          echo "Adding default label to discussion #${{ github.event.discussion.number }}"

          # Add the default label using the Issues API (works for discussions too)
          curl -X POST -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.discussion.number }}/labels \
            -d "{\"labels\":[\"$LABEL\"]}"

          echo "Label $LABEL has been added to discussion #${{ github.event.discussion.number }}"
