name: Label Discussions

on:
  discussion:
    types: [created]

jobs:
  label_discussion:
    runs-on: ubuntu-latest

    steps:
      - name: Add label to discussion
        env:
          GH_TOKEN: ${{ secrets.G_TOKEN }}
          DISCUSSION_NUMBER: ${{ github.event.discussion.number }}
          LABEL: ideas
        run: |
          echo "Adding label $LABEL to discussion #${{ github.event.discussion.number }}"

          # Adding the label using the GitHub Issues API (works for discussions as well)
          RESPONSE=$(curl -s -X POST -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.discussion.number }}/labels \
            -d "{\"labels\":[\"$LABEL\"]}")

          echo "Response: $RESPONSE"
