name: Provision EC2 from Discussion

on:
  discussion_comment:
    types: [created]

jobs:
  extract-inputs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract configuration from discussion
        id: extract_config
        run: |
          # Fetch the comment body content and extract the necessary parameters
          DISCUSSION_BODY="${{ github.event.comment.body }}"
          
          # Extract each input field from the comment
          INSTANCE_TYPE=$(echo "$DISCUSSION_BODY" | grep "EC2 Instance Type" -A 1 | tail -n 1 | xargs)
          VPC_ID=$(echo "$DISCUSSION_BODY" | grep "VPC ID" -A 1 | tail -n 1 | xargs)
          SECURITY_GROUP_ID=$(echo "$DISCUSSION_BODY" | grep "Security Group ID" -A 1 | tail -n 1 | xargs)
          REGION=$(echo "$DISCUSSION_BODY" | grep "AWS Region" -A 1 | tail -n 1 | xargs)
          KEY_PAIR=$(echo "$DISCUSSION_BODY" | grep "Key Pair Name" -A 1 | tail -n 1 | xargs)

          # Set these as outputs for the next step
          echo "::set-output name=instance_type::$INSTANCE_TYPE"
          echo "::set-output name=vpc_id::$VPC_ID"
          echo "::set-output name=security_group_id::$SECURITY_GROUP_ID"
          echo "::set-output name=region::$REGION"
          echo "::set-output name=key_pair::$KEY_PAIR"

  deploy-cdk:
    needs: extract-inputs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ steps.extract_config.outputs.region }}

      - name: Deploy EC2 with AWS CDK
        run: |
          cdk deploy MyEc2Stack \
            --parameters instanceType=${{ steps.extract_config.outputs.instance_type }} \
            --parameters vpcId=${{ steps.extract_config.outputs.vpc_id }} \
            --parameters securityGroupId=${{ steps.extract_config.outputs.security_group_id }} \
            --parameters keyPairName=${{ steps.extract_config.outputs.key_pair }}
